# Site settings
baseurl = "https://ragamatrix.github.io/"
languageCode = "en-us"
title = "the photo is made through musical inspiration"
theme = "photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    no_exif = false
    title = "elsewhere it is here"
    subtitle = "a glimpse through the window"
    author = "@raphael.buy"
    description = "pix gallery"
    keywords = "Hugo, Hugo theme, grid theme, gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "© 2021 Raphaël Buy --> [@raphael.buy](https://instagram.com/raphael.buy) -- [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)"
